[env]
platform = teensy
board = teensy41
framework = arduino

build_src_filter =
    +<*.cpp> +<*.c>

    +<usb/*.c> +<usb/*.cpp>
    +<mj9k/*.c> +<mj9k/*.cpp>
    +<switches/*.c> +<switches/*.cpp>

    ; USB Library
    +<tinyusb/src/*.c>
    +<tinyusb/src/class/*>
    +<tinyusb/src/common/*.c>
    +<tinyusb/src/device/*.c>
    +<tinyusb/src/host/*.c>
    +<tinyusb/src/portable/ehci/*.c>
    +<tinyusb/src/portable/chipidea/ci_hs/*.c>
    +<tinyusb/hw/mcu/nxp/mcux-sdk/devices/MIMXRT1062/*.c>

build_flags =
    -Isrc/usb

    ; USB Library
    -Isrc/tinyusb/src
    -Isrc/tinyusb/src/device
    -Isrc/tinyusb/src/host
    -Isrc/tinyusb/lib/CMSIS_5/CMSIS/Core/Include
    -Isrc/tinyusb/hw/mcu/nxp/mcux-sdk/devices/MIMXRT1062

    -DCPU_MIMXRT1062DVL6A
    -DCFG_TUSB_MCU=OPT_MCU_MIMXRT10XX
    -DCFG_TUSB_DEBUG=1 ; 0 = Off, 1 = Error, 2 = Warn, 3 = Debug
    -DCFG_TUSB_DEBUG_PRINTF="printf"

    ; The serial port that printf will output to
    -DSERDBG="Serial7"

[env:release]
